### ISSUE TITLE
Sites that have a huge amount of posts it crashes

### ISSUE THREAD

**Issue by fabiankaegy** [eddysims/find-my-blocks#44]
I'm of course not sure wether there is anything you can really easily do about this, but maybe with pagination processing them in chunks rather than all at once might be a cool idea. 

When I change:

```php
$posts = get_posts(
	array(
		'posts_per_page' => -1,
		'post_type'      => $post_type,
	)
);
```

to 

```php
$posts = get_posts(
	array(
		'posts_per_page' => 100,
		'post_type'      => $post_type,
	)
);
```

in `inc/register_route.php` it works.

And maybe having an error handler that tells you when the request didn't work might be a nice addition :) Currently the block rotation animation just keeps spinning endlessly

**Comment by eddysims** [comment]
Hey @fabiankaegy this is being talked about in https://github.com/eddysims/find-my-blocks/issues/36 as well.

**Comment by eddysims** [comment]
I have moved this comment, and will close this issue.
