### ISSUE TITLE
Stackable blocks not showing

### ISSUE THREAD

**Issue by eddysims** [eddysims/find-my-blocks#47]
https://wordpress.org/support/topic/question-about-refresh-and-certain-blocks/

**Comment by thomas-price** [comment]
Hi Eddy,
It seems a few users of this plugin are finding blocks inside nested blocks are not getting picked up.
I have some container blocks in a site I’m maintaining that are showing up in the plugin but their contents are not.

Would be great to see it resolved

regards
Thomas

**Comment by thomas-price** [comment]
I am thinking many users will have a similar use case: They want to know all the instances of **one** block.
Your current solution tries to show all instances of **all** blocks. For larger sites, this may cause load issues.
A possible solution could be to make the console interactive (ajax) and allow the user to select one block to search for.
On click, the search is undertaken (including nested blocks) and results presented.
It doesn't matter if it takes a while, users will be happy to wait 5 - 15 sec (size of content dependent)

**Comment by cjyabraham** [comment]
I have made the find-my-blocks plugin recursively find all blocks and nested blocks.  <a href="https://github.com/LF-Engineering/lfevents/commit/60ba5c4cee91862580a4338726557a62a74e156d#diff-51a1d311883aa4d9f82ec16af5aa558c">Here is the changeset</a>.  

To use it yourself, just replace the register-route.php file with <a href="https://github.com/LF-Engineering/lfevents/blob/stkbl-migrate/web/wp-content/plugins/find-my-blocks/inc/register-route.php">this version</a>.  Let me know if it doesn't work.

**Comment by eddysims** [comment]
> I have made the find-my-blocks plugin recursively find all blocks and nested blocks. [Here is the changeset](https://github.com/LF-Engineering/lfevents/commit/60ba5c4cee91862580a4338726557a62a74e156d#diff-51a1d311883aa4d9f82ec16af5aa558c).
> 
> To use it yourself, just replace the register-route.php file with [this version](https://github.com/LF-Engineering/lfevents/blob/stkbl-migrate/web/wp-content/plugins/find-my-blocks/inc/register-route.php). Let me know if it doesn't work.

Do you want to make this into a pull request?

**Comment by cjyabraham** [comment]
Sure.  [Here it is](https://github.com/eddysims/find-my-blocks/pull/58).
