### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by FriendlyWP** [eddysims/find-my-blocks#55]
I'm seeing this console error on the find-my-blocks page in the control panel (v. 2.2.0 / WP 5.5), not sure if it matters but just in case:

`find-my-blocks.js?ver=1597855137:589 You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.`

I love the plugin, thank you!

**Comment by eddysims** [comment]
@FriendlyWP this has been fixed in `v3.1.1` sorry for the late reply.
